
(function(){
var params=new URLSearchParams(location.search);var state={affiliates:[],members:[],referralRows:[],client:null,filterStat:params.get('filter')||'all',rewardFilter:params.get('reward')||'all',pendingDelete:null,source:'local',view:params.get('view')||'overview'};
function el(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}function norm(v){return String(v==null?'':v).trim().toLowerCase()}function pick(o,keys){for(var i=0;i<keys.length;i++){if(o&&o[keys[i]]!=null&&String(o[keys[i]]).trim()!=='')return o[keys[i]]}return ''}function getJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||'')}catch(e){return d}}function setJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}function toast(msg){var t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},2600)}
function cfg(){var c=window.KAMAR_CONFIG||window.KamarConfig||window.kamarConfig||{};return {url:c.supabaseUrl||c.SUPABASE_URL||c.url||window.KAMAR_SUPABASE_URL||'',key:c.supabaseAnonKey||c.SUPABASE_ANON_KEY||c.anonKey||window.KAMAR_SUPABASE_ANON_KEY||''}}
function client(){if(state.client)return state.client;var ex=window.kamarSupabaseClient||window.KamarSupabaseClient||(window.KamarSupabase&&window.KamarSupabase.client)||(window.KamarSB&&window.KamarSB.client)||(window.kamarSupabase&&window.kamarSupabase.client);if(ex){state.client=ex;return ex}var c=cfg();if(window.supabase&&window.supabase.createClient&&c.url&&c.key){state.client=window.supabase.createClient(c.url,c.key);return state.client}return null}
async function query(table){var c=client();if(!c)throw new Error('Supabase tidak tersedia');var res=await c.from(table).select('*').limit(1000);if(res.error)throw res.error;return res.data||[]}
function nameOf(r){return String(pick(r,['full_name','fullName','name','display_name','member_name','affiliate_name','username'])||'')}function emailOf(r){return String(pick(r,['email','email_address','member_email','affiliate_email'])||'')}function waOf(r){return String(pick(r,['whatsapp','wa','phone','phone_number','nomor_wa','affiliate_whatsapp'])||'')}function tgOf(r){return String(pick(r,['telegram','telegram_username','tg'])||'')}function idOf(r){return String(pick(r,['member_id','id','user_id','profile_id','uuid'])||'')}function codeOf(r){return String(pick(r,['referralCode','referral_code','kode_referral','ref_code','affiliate_code','used_referral_code','referred_by_code','code'])||'')}function rowKey(r){return norm(idOf(r)||emailOf(r)||waOf(r)||nameOf(r))}
function localAffiliates(){var out=[];['kamarAffiliateList','kamarAffiliateSession','kamarAffiliateDraft'].forEach(function(k){var v=getJSON(k,null);if(Array.isArray(v))out=out.concat(v);else if(v&&typeof v==='object')out.push(v)});return out}
function normalizeAffiliate(a){a=a||{};var p=a.payoutAccount||a.payout||{};var code=codeOf(a)||String(pick(a,['code'])||'');return Object.assign({},a,{_rowKey:rowKey(a)||norm(code),fullName:nameOf(a)||'Affiliator Kamar',email:emailOf(a),whatsapp:waOf(a),telegram:tgOf(a),referralCode:code,payoutAccount:{fullName:pick(p,['fullName','holder','account_name','nama_rekening','name'])||pick(a,['payout_name','bank_account_name','account_name']),bankName:pick(p,['bankName','bank','bank_name','nama_bank'])||pick(a,['bank_name','bank']),accountNumber:pick(p,['accountNumber','account_number','rekening','nomor_rekening'])||pick(a,['account_number','rekening']),verificationStatus:pick(p,['verificationStatus','status'])||pick(a,['payout_status','bank_status'])},payoutVerified:!!(a.payoutVerified||a.payout_verified||/verified|terverifikasi|valid/i.test(String(pick(a,['payout_status','bank_status'])||'')))})}
function dedupeAffiliates(list){var map={};list.map(normalizeAffiliate).forEach(function(a){var byPerson=norm(a.email||a.whatsapp||a.fullName);var byCode=norm(a.referralCode);var key=byPerson||byCode;if(!key)return;if(!map[key])map[key]=a;else{var old=map[key];var oldScore=(old.referralCode?1:0)+(old.email?1:0)+(old.whatsapp?1:0);var newScore=(a.referralCode?1:0)+(a.email?1:0)+(a.whatsapp?1:0);if(newScore>=oldScore)map[key]=Object.assign({},old,a,{payoutAccount:Object.assign({},old.payoutAccount||{},a.payoutAccount||{})})}});return Object.keys(map).map(function(k){return map[k]})}
function mergeRows(){var map={};for(var a=0;a<arguments.length;a++){(arguments[a]||[]).forEach(function(r){var k=rowKey(r);if(k)map[k]=Object.assign(map[k]||{},r)})}return Object.keys(map).map(function(k){return map[k]})}
function hasIdentity(m){return !!(nameOf(m)||emailOf(m)||waOf(m)||tgOf(m))}function isInternal(m){var txt=norm([nameOf(m),emailOf(m),pick(m,['role','account_type','type'])].join(' '));return txt.indexOf('kamarkajianmarket@gmail.com')>=0||txt.indexOf('admin')>=0||txt==='kamarkajianmarket'}function facilitiesOf(m){var raw=pick(m,['facilities','active_facilities','facility','access_facilities']);if(Array.isArray(raw))return raw.filter(Boolean);if(typeof raw==='string'&&raw.trim()){try{var arr=JSON.parse(raw);if(Array.isArray(arr))return arr}catch(e){}return raw.split(',').map(function(x){return x.trim()}).filter(Boolean)}var out=[];['kamar_study','kamar_edukasi','kamar_private','kamar_indikator','kamar_robot'].forEach(function(k){if(m[k]===true||m[k]==='true'||m[k]===1)out.push(k.replace('kamar_','Kamar ').replace(/\b\w/g,function(c){return c.toUpperCase()}))});return out}
function payoutState(a){var p=a.payoutAccount||{};if(a.payoutVerified||/terverifikasi|verified|valid/i.test(String(p.verificationStatus||'')))return 'verified';if(p.fullName&&p.bankName&&p.accountNumber)return 'ready';return 'empty'}function payoutLabel(a){var s=payoutState(a);if(s==='verified')return '<span class="pill ok">Rekening Valid</span>';if(s==='ready')return '<span class="pill warn">Perlu Verifikasi</span>';return '<span class="pill off">Belum Isi Rekening</span>'}function statusLabel(m){var s=norm(pick(m,['status','account_status','status_key','member_status']));if(s.indexOf('active')>=0||s.indexOf('aktif')>=0)return '<span class="pill ok">Aktif</span>';if(s.indexOf('pending')>=0)return '<span class="pill warn">Pending</span>';return '<span class="pill off">-</span>'}
function refsFor(code){code=norm(code);if(!code)return [];var refs=state.members.filter(function(m){return norm(codeOf(m))===code});(state.referralRows||[]).forEach(function(r){if(norm(codeOf(r))===code&&!refs.some(function(m){return rowKey(m)===rowKey(r)}))refs.push(r)});return refs}

function rewardStore(){return getJSON('kamarAffiliateRewardStatus',{})||{}}
function saveRewardStore(o){setJSON('kamarAffiliateRewardStatus',o||{})}
function rewardKey(a,m){return norm((a&&a.referralCode||'')+'::'+(idOf(m)||emailOf(m)||nameOf(m)||''))}
function rewardStatus(a,m){var st=rewardStore()[rewardKey(a,m)]||{};return st.status==='paid'?'paid':'unpaid'}
function rewardMeta(a,m){return rewardStore()[rewardKey(a,m)]||{}}
function rewardRows(){var rows=[];state.affiliates.forEach(function(a){refsFor(a.referralCode).forEach(function(m){rows.push({affiliate:a,member:m,key:rewardKey(a,m),status:rewardStatus(a,m),meta:rewardMeta(a,m)})})});return rows}
function rewardLabel(status){return status==='paid'?'<span class="pill paid">Sudah Dibayar</span>':'<span class="pill unpaid">Belum Dibayar</span>'}
function formatMoney(v){var n=Number(String(v||'').replace(/[^0-9]/g,''));if(!n)return 'Belum diatur';return 'Rp'+n.toLocaleString('id-ID')}
function renderRewards(){var list=rewardRows();var f=state.rewardFilter||'all';var arr=list.filter(function(r){return f==='all'||r.status===f});var paid=list.filter(function(r){return r.status==='paid'}).length;var unpaid=list.filter(function(r){return r.status!=='paid'}).length;if(el('statRewardPaid'))el('statRewardPaid').textContent=paid;if(el('statRewardUnpaid'))el('statRewardUnpaid').textContent=unpaid;var h='<div class="reward-row head"><div>Affiliator</div><div>Member Referral</div><div>Fasilitas</div><div>Nominal Reward</div><div>Status</div><div>Aksi</div></div>';if(!list.length)h+='<div class="empty">Belum ada referral yang bisa dihitung sebagai reward.</div>';else if(!arr.length)h+='<div class="empty">Tidak ada reward sesuai filter.</div>';arr.forEach(function(r){var a=r.affiliate,m=r.member,fac=facilitiesOf(m),meta=r.meta||{};h+='<div class="reward-row"><div><strong>'+esc(a.fullName||'-')+'</strong><small class="info-small">Kode: '+esc(a.referralCode||'-')+'</small></div><div><strong>'+esc(nameOf(m)||'Member Kamar')+'</strong><small class="info-small">'+esc(emailOf(m)||'-')+'</small></div><div>'+esc(fac.length?fac.join(', '):'Belum ada fasilitas aktif')+'</div><div><input class="money-input" data-reward-amount="'+esc(r.key)+'" value="'+esc(meta.amount||'')+'" placeholder="Rp"></div><div>'+rewardLabel(r.status)+'<div class="note-line">'+(meta.paidAt?'Dibayar: '+esc(meta.paidAt):'Menunggu pembayaran reward')+'</div></div><div class="row-actions"><button class="btn small" data-save-reward="'+esc(r.key)+'">Simpan</button>'+(r.status==='paid'?'<button class="btn danger small" data-unpay-reward="'+esc(r.key)+'">Batalkan</button>':'<button class="btn secondary small" data-pay-reward="'+esc(r.key)+'">Tandai Dibayar</button>')+'</div></div>'});el('rewardList').innerHTML=h;wireRewardRows()}
function setRewardStatus(key,status){var store=rewardStore();store[key]=store[key]||{};store[key].status=status;if(status==='paid')store[key].paidAt=new Date().toLocaleString('id-ID');else delete store[key].paidAt;saveRewardStore(store);toast(status==='paid'?'Reward ditandai sudah dibayar.':'Status reward dikembalikan ke belum dibayar.');renderRewards()}
function saveRewardAmount(key){var input=null;document.querySelectorAll('[data-reward-amount]').forEach(function(i){if(i.getAttribute('data-reward-amount')===key)input=i});var store=rewardStore();store[key]=store[key]||{};store[key].amount=input?input.value:'';saveRewardStore(store);toast('Nominal reward disimpan.');renderRewards()}
function wireRewardRows(){document.querySelectorAll('[data-pay-reward]').forEach(function(b){b.onclick=function(){setRewardStatus(b.getAttribute('data-pay-reward'),'paid')}});document.querySelectorAll('[data-unpay-reward]').forEach(function(b){b.onclick=function(){setRewardStatus(b.getAttribute('data-unpay-reward'),'unpaid')}});document.querySelectorAll('[data-save-reward]').forEach(function(b){b.onclick=function(){saveRewardAmount(b.getAttribute('data-save-reward'))}})}

function normalizeView(v){return ['overview','list','reward'].indexOf(v)>=0?v:'overview'}
function setView(v){state.view=normalizeView(v);document.querySelectorAll('[data-view-section]').forEach(function(x){x.classList.toggle('view-hidden',x.getAttribute('data-view-section')!==state.view)});document.querySelectorAll('[data-aff-tab],[data-aff-menu]').forEach(function(x){var active=x.getAttribute('data-aff-tab')===state.view||x.getAttribute('data-aff-menu')===state.view;x.classList.toggle('active',active)});var title='Data Affiliate',desc='Ringkasan besar affiliate, referral, rekening, dan reward.';if(state.view==='list'){title='Daftar Affiliator';desc='Kelola nama affiliator, kode referral, detail, salin kode, verifikasi rekening, dan hapus affiliator.'}if(state.view==='reward'){title='Reward / Komisi Affiliate';desc='Pantau nominal reward, status belum dibayar, sudah dibayar, dan tanggal pembayaran reward.'}if(el('viewTitle'))el('viewTitle').textContent=title;if(el('viewDesc'))el('viewDesc').textContent=desc;}
function goView(v,extra){var u=new URL(location.href);u.searchParams.set('view',v);u.searchParams.set('v','24dn');if(extra){Object.keys(extra).forEach(function(k){if(extra[k]==null)u.searchParams.delete(k);else u.searchParams.set(k,extra[k])})}history.replaceState(null,'',u.pathname+u.search);setView(v)}
async function load(){el('affiliateList').innerHTML='<div class="empty">Memuat data affiliate...</div>';try{var view=await query('admin_member_overview');var prof=await query('member_profiles');var acc=[];try{acc=await query('member_access')}catch(e){}state.members=mergeRows(view,prof,acc).filter(function(m){return hasIdentity(m)&&!isInternal(m)});try{var aff=await query('affiliates');state.affiliates=dedupeAffiliates(aff&&aff.length?aff:localAffiliates());state.source=aff&&aff.length?'supabase':'local'}catch(e){state.affiliates=dedupeAffiliates(localAffiliates());state.source='local'}try{state.referralRows=await query('affiliate_referrals')}catch(e){state.referralRows=[]}}catch(e){state.members=getJSON('kamarRegisteredMembers',[]).filter(hasIdentity);state.affiliates=dedupeAffiliates(localAffiliates());state.referralRows=[];state.source='local'}render()}
function updateStats(){var totalRef=0,valid=0,empty=0;state.affiliates.forEach(function(a){totalRef+=refsFor(a.referralCode).length;var s=payoutState(a);if(s==='verified')valid++;if(s==='empty')empty++});el('statAff').textContent=state.affiliates.length;el('statRef').textContent=totalRef;el('statVerified').textContent=valid;el('statEmpty').textContent=empty}
function filtered(){var q=norm(el('affiliateSearch').value), f=el('payoutFilter').value, sf=state.filterStat;return state.affiliates.filter(function(a){var text=norm([a.fullName,a.referralCode,a.email,a.whatsapp].join(' '));var ok=!q||text.indexOf(q)>=0;var ps=payoutState(a);if(f!=='all'&&ps!==f)ok=false;if(sf==='verified'&&ps!=='verified')ok=false;if(sf==='empty'&&ps!=='empty')ok=false;if(sf==='hasRef'&&refsFor(a.referralCode).length<1)ok=false;return ok})}
function render(){updateStats();var arr=filtered();var h='<div class="aff-row head"><div>Affiliator</div><div>Kode Referral</div><div>Total Referral</div><div>Status Rekening</div><div>Aksi</div></div>';if(!state.affiliates.length)h+='<div class="empty">Belum ada affiliator terdaftar.</div>';else if(!arr.length)h+='<div class="empty">Tidak ada affiliator yang sesuai filter.</div>';arr.forEach(function(a){var code=a.referralCode||'-';h+='<div class="aff-row"><div class="aff-name"><strong>'+esc(a.fullName)+'</strong><small>'+esc(a.email||'-')+' · WA: '+esc(a.whatsapp||'-')+'</small></div><div class="aff-code"><strong>'+esc(code)+'</strong></div><div>'+refsFor(code).length+' member</div><div>'+payoutLabel(a)+'</div><div class="row-actions"><button class="btn small" data-detail="'+esc(code)+'">Detail</button><button class="btn secondary small" data-copy="'+esc(code)+'">Salin</button><button class="btn danger small" data-delete="'+esc(code)+'">Hapus</button></div></div>'});el('affiliateList').innerHTML=h;wireRows();renderRewards()}
function findAff(code){code=norm(code);return state.affiliates.find(function(a){return norm(a.referralCode)===code})}
function showDetail(code){var a=findAff(code);if(!a)return;var p=a.payoutAccount||{}, refs=refsFor(a.referralCode);var rows='';if(!refs.length)rows='<div class="empty">Belum ada member referral dari kode ini.</div>';else rows='<div class="ref-row head"><div>Member</div><div>Kontak</div><div>Kode</div><div>Fasilitas</div><div>Status</div></div>'+refs.map(function(m){var fac=facilitiesOf(m);return '<div class="ref-row"><div><strong>'+esc(nameOf(m)||'Member Kamar')+'</strong><small class="info-small">'+esc(idOf(m)||'-')+'</small></div><div>'+esc(emailOf(m)||'-')+'<small class="info-small">WA: '+esc(waOf(m)||'-')+' · TG: '+esc(tgOf(m)||'-')+'</small></div><div>'+esc(a.referralCode||'-')+'</div><div>'+esc(fac.length?fac.join(', '):'Belum ada fasilitas aktif')+'</div><div>'+statusLabel(m)+'</div></div>'}).join('');var verify='';if(payoutState(a)==='ready')verify='<button class="btn small" data-verify="'+esc(a.referralCode)+'">Verifikasi Rekening</button>';if(payoutState(a)==='verified')verify='<button class="btn danger small" data-unverify="'+esc(a.referralCode)+'">Batalkan Verifikasi</button>';
el('detailCard').innerHTML='<div class="detail-head"><div><h2>Detail Affiliator</h2><p>'+esc(a.fullName)+' · '+esc(a.referralCode||'-')+'</p></div><div class="detail-actions"><button class="btn secondary small" data-copy="'+esc(a.referralCode)+'">Salin Kode</button>'+verify+'<button class="btn secondary small" id="closeDetail">Tutup</button></div></div><div class="detail-grid"><div class="panel"><h3>Profil Affiliator</h3><div class="info-grid"><div class="info-item"><span>Nama</span><strong>'+esc(a.fullName||'-')+'</strong></div><div class="info-item"><span>Kode Referral</span><strong>'+esc(a.referralCode||'-')+'</strong></div><div class="info-item"><span>Total Referral</span><strong>'+refs.length+' member</strong></div><div class="info-item"><span>Status Rekening</span>'+payoutLabel(a)+'</div><div class="info-item"><span>Email</span><strong>'+esc(a.email||'-')+'</strong></div><div class="info-item"><span>WhatsApp</span><strong>'+esc(a.whatsapp||'-')+'</strong></div></div></div><div class="panel"><h3>Akun Penerima Pembayaran</h3><div class="pay-list"><div class="pay-line"><b>Nama</b><span>'+esc(p.fullName||'-')+'</span></div><div class="pay-line"><b>Bank</b><span>'+esc(p.bankName||'-')+'</span></div><div class="pay-line"><b>Rekening</b><span>'+esc(p.accountNumber||'-')+'</span></div><div class="pay-line"><b>Catatan</b><span>KTP tidak disimpan di website. Verifikasi dokumen dilakukan manual melalui admin resmi.</span></div></div></div><div class="panel ref-panel"><h3>Daftar Referral</h3><div class="ref-table">'+rows+'</div></div></div>';
el('detailCard').classList.add('show');wireRows();el('closeDetail')&&(el('closeDetail').onclick=function(){el('detailCard').classList.remove('show')});el('detailCard').scrollIntoView({behavior:'smooth',block:'start'})}
function saveLocal(list){setJSON('kamarAffiliateList',list)}function removeLocal(code){var c=norm(code);['kamarAffiliateList','kamarAffiliateSession','kamarAffiliateDraft'].forEach(function(k){var v=getJSON(k,null);if(Array.isArray(v))setJSON(k,v.filter(function(a){return norm(codeOf(a))!==c}));else if(v&&typeof v==='object'&&norm(codeOf(v))===c)localStorage.removeItem(k)})}
async function deleteAffiliate(code){var a=findAff(code);if(!a)return;removeLocal(code);state.affiliates=state.affiliates.filter(function(x){return norm(x.referralCode)!==norm(code)});var c=client();if(c){try{if(a.id)await c.from('affiliates').delete().eq('id',a.id);else if(a.referralCode)await c.from('affiliates').delete().eq('referral_code',a.referralCode)}catch(e){}}
el('detailCard').classList.remove('show');toast('Affiliator dihapus dari daftar.');render()}
function verify(code,on){var a=findAff(code);if(!a)return;a.payoutVerified=!!on;if(a.payoutAccount)a.payoutAccount.verificationStatus=on?'Terverifikasi Admin':'Menunggu Verifikasi';var list=dedupeAffiliates(localAffiliates());var idx=list.findIndex(function(x){return norm(x.referralCode)===norm(code)});if(idx>=0)list[idx]=a;else list.push(a);saveLocal(list);toast(on?'Rekening berhasil diverifikasi.':'Verifikasi rekening dibatalkan.');render();showDetail(code)}
function wireRows(){document.querySelectorAll('[data-detail]').forEach(function(b){b.onclick=function(){showDetail(b.getAttribute('data-detail'))}});document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var c=b.getAttribute('data-copy')||'';navigator.clipboard&&navigator.clipboard.writeText(c);toast('Kode referral disalin: '+c)}});document.querySelectorAll('[data-delete]').forEach(function(b){b.onclick=function(){state.pendingDelete=b.getAttribute('data-delete');var a=findAff(state.pendingDelete);el('confirmText').textContent='Hapus affiliator '+(a?a.fullName:'ini')+' dari daftar admin? Tindakan ini dipakai untuk data duplikat atau affiliator yang memang tidak digunakan.';el('confirmModal').classList.add('show')}});document.querySelectorAll('[data-verify]').forEach(function(b){b.onclick=function(){verify(b.getAttribute('data-verify'),true)}});document.querySelectorAll('[data-unverify]').forEach(function(b){b.onclick=function(){verify(b.getAttribute('data-unverify'),false)}})}
document.querySelectorAll('[data-stat-filter]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();state.filterStat=a.getAttribute('data-stat-filter')||'all';if(state.filterStat==='verified')el('payoutFilter').value='verified';else if(state.filterStat==='empty')el('payoutFilter').value='empty';else el('payoutFilter').value='all';goView('list',{filter:state.filterStat,reward:null});render();el('affiliateListCard').scrollIntoView({behavior:'smooth',block:'start'})})});

document.querySelectorAll('[data-reward-filter]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();state.rewardFilter=a.getAttribute('data-reward-filter')||'all';el('rewardFilter').value=state.rewardFilter;goView('reward',{reward:state.rewardFilter,filter:null});renderRewards();el('rewardCard').scrollIntoView({behavior:'smooth',block:'start'})})});
if(el('rewardFilter'))el('rewardFilter').value=state.rewardFilter||'all';el('rewardFilter').addEventListener('change',function(){state.rewardFilter=el('rewardFilter').value;goView('reward',{reward:state.rewardFilter});renderRewards()});el('resetRewardFilter').onclick=function(){state.rewardFilter='all';el('rewardFilter').value='all';goView('reward',{reward:'all'});renderRewards()};
el('affiliateSearch').addEventListener('input',render);el('payoutFilter').addEventListener('change',function(){state.filterStat='all';render()});el('applyAffiliateFilter').onclick=function(){state.filterStat='all';render()};el('resetAffiliateFilter').onclick=function(){state.filterStat='all';el('affiliateSearch').value='';el('payoutFilter').value='all';render()};el('refreshBtn').onclick=load;el('cancelDelete').onclick=function(){state.pendingDelete=null;el('confirmModal').classList.remove('show')};el('confirmDelete').onclick=function(){var c=state.pendingDelete;state.pendingDelete=null;el('confirmModal').classList.remove('show');deleteAffiliate(c)};el('exportBtn').onclick=function(){var rows=[['Nama','Email','WA','Kode Referral','Total Referral','Status Rekening','Nama Rekening','Bank','Nomor Rekening','Reward Belum Dibayar','Reward Dibayar']];state.affiliates.forEach(function(a){var p=a.payoutAccount||{};rows.push([a.fullName,a.email,a.whatsapp,a.referralCode,refsFor(a.referralCode).length,payoutState(a),p.fullName||'',p.bankName||'',p.accountNumber||'',refsFor(a.referralCode).filter(function(m){return rewardStatus(a,m)!=='paid'}).length,refsFor(a.referralCode).filter(function(m){return rewardStatus(a,m)==='paid'}).length])});var csv=rows.map(function(r){return r.map(function(x){return '"'+String(x==null?'':x).replace(/"/g,'""')+'"'}).join(',')}).join('\n');var blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='data-affiliate-kamar.csv';link.click();URL.revokeObjectURL(url)};
function init(){setView(state.view);if(state.filterStat==='verified')el('payoutFilter').value='verified';else if(state.filterStat==='empty')el('payoutFilter').value='empty';else el('payoutFilter').value='all';if(el('rewardFilter'))el('rewardFilter').value=state.rewardFilter||'all';load()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
